config/routes.rb
TrackImportantDates::Application.routes.draw do
  root :to => "important_dates#index"
  resources :important_dates

end

app/models/important_date.rb
class ImportantDate < ActiveRecord::Base
  attr_accessible :date_of_importance, :description, :importance, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/important_dates_controller.rb
class ImportantDatesController < ApplicationController
  def index
    @important_dates = ImportantDate.select {|d| d.date_of_importance >= Date.today}
  end

  def new
    @important_date = ImportantDate.new
  end

  def create
    @important_date = ImportantDate.new(params[:important_date])
    if @important_date.save
      flash[:notice] = "Important Date has been created"
      redirect_to @important_date
    else
    end
  end

  def show
    @important_date = ImportantDate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/important_dates_helper.rb
module ImportantDatesHelper
end

app/views/important_dates/index.html.erb
<h1>Listing Important Dates</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Description</th>
    <th>Importance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @important_dates.each do |date| %>
  <tr>
    <td><%= date.name %></td>
    <td><%= date.date_of_importance %></td>
    <td><%= date.description %></td>
    <td><%= date.importance %></td>
    <td><%= link_to 'Show', date %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "New Important Date", new_important_date_path %>

app/views/important_dates/new.html.erb
<h2>New Important Date</h2>
<%= form_for(@important_date) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :date_of_importance %><br />
    <%= f.date_select :date_of_importance, :start_year => Date.today.year - 100 %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :importance %><br />
    <%= f.text_field :importance %>
  </p>
  <%= f.submit %>
<% end %>

app/views/important_dates/show.html.erb
<h2><%= @important_date.name %></h2>
<p>Date of Importance: <%= @important_date.date_of_importance %></p>
<p>Description: <%= @important_date.description %></p>
<p>Importance: <%= @important_date.importance %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TrackImportantDates</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>